[project]
name = "img-enhancer"
version = "0.1.0"
description = "Image Enhancer"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pillow==9.3.0",
    "rembg==2.0.31",
    "streamlit==1.24.1",
]